import type { Metadata } from "next";
import { Ubuntu, Noto_Sans, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/providers";
import { Toaster } from "sonner";

const ubuntu = Ubuntu({
    variable: "--font-ubuntu",
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
});

const notoSans = Noto_Sans({
    variable: "--font-noto-sans",
    subsets: ["latin"],
});

const notoMono = Noto_Sans_Mono({
    variable: "--font-noto-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${ubuntu.variable} ${notoSans.variable} ${notoMono.variable} antialiased`}
            >
                <Providers>{children}</Providers>
                <Toaster />
            </body>
        </html>
    );
}
