export const dietaryOptions = [
    "Vegan",
    "Vegetarian",
    "Keto",
    "GlutenFree",
    "Paleo",
    "LowCarb",
    "HighProtein",
    "DairyFree",
    "NutFree",
    "Halal",
    "Kosher",
    "Pescatarian",
    "SugarFree",
    "Organic",
] 